spec:
  containers:
    - name: restore
      image: ${POSTGRES_IMAGE:-ghcr.io/snowflake-labs/postgres-client:16}
      command:
        - bash
        - -lc
        - |
          set -euo pipefail
          pg_restore \
            --dbname "$SUPERSET_DB_URI" \
            --no-owner \
            --clean \
            /stage/superset.dump
      volumeMounts:
        - name: dump
          mountPath: /stage
      env:
        - name: SUPERSET_DB_URI
          valueFrom:
            secretRef:
              name: superset_meta_pg
              key: uri
  volumes:
    - name: dump
      source: stage
      stageConfig:
        name: ${DUMP_STAGE:-@app_artifacts.superset_dump}
