spec:
  containers:
    - name: superset
      image: ${SPCS_IMAGE}
      command:
        - bash
        - /app/scripts/spcs_allinone_start.sh
      env:
        SUPERSET_CONFIG_PATH: /config/superset_config.py
        # In SPCS, containers in the same service instance share a network namespace;
        # use localhost instead of container names for intra-service connections.
        SUPERSET_DB_URI: "postgresql+psycopg2://superset:superset@localhost:5432/superset"
        SUPERSET_REDIS_HOST: localhost
        SUPERSET_REDIS_PORT: "6379"
        SUPERSET_SECRET_KEY: "${SUPERSET_SECRET_KEY_VALUE}"
        SUPERSET_FERNET_KEY: "${SUPERSET_FERNET_KEY_VALUE}"
        SUPERSET_BOOTSTRAP_ADMINS: "${SUPERSET_ADMINS_VALUE}"
      volumeMounts:
        - name: superset-config
          mountPath: /config
      resources:
        requests:
          cpu: "0.5"
          memory: 2Gi
        limits:
          cpu: "0.5"
          memory: 2Gi

    - name: postgres
      image: ${SPCS_POSTGRES_IMAGE}
      env:
        POSTGRES_DB: superset
        POSTGRES_USER: superset
        POSTGRES_PASSWORD: superset
        # Block volumes can be mounted as a filesystem root containing `lost+found`.
        # Postgres refuses to initdb directly in such a directory, so use a subdir.
        PGDATA: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      resources:
        requests:
          cpu: "0.25"
          memory: 1Gi
        limits:
          cpu: "0.5"
          memory: 2Gi

    - name: redis
      image: ${SPCS_REDIS_IMAGE}
      command: ["redis-server","--save","","--appendonly","no"]
      resources:
        requests:
          cpu: "0.25"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi

  endpoints:
    - name: ui
      port: 8088
      public: true

  volumes:
    - name: superset-config
      source: stage
      stageConfig:
        name: "${CONFIG_STAGE}"
    - name: pgdata
      source: block
      size: 5Gi
