spec:
  containers:
    - name: superset
      image: ${SPCS_IMAGE}
      env:
        SUPERSET_CONFIG_PATH: /config/superset_config.py
        SUPERSET_REDIS_HOST: redis
        SUPERSET_REDIS_PORT: "6379"
      secrets:
        - snowflakeSecret: ${SECRET_SUPERSET_DB_URI}
          secretKeyRef: secret_string
          envVarName: SUPERSET_DB_URI
        - snowflakeSecret: ${SECRET_SUPERSET_SECRET_KEY}
          secretKeyRef: secret_string
          envVarName: SUPERSET_SECRET_KEY
        - snowflakeSecret: ${SECRET_SUPERSET_FERNET_KEY}
          secretKeyRef: secret_string
          envVarName: SUPERSET_FERNET_KEY
      volumeMounts:
        - name: superset-config
          mountPath: /config
      resources:
        requests:
          cpu: "0.75"
          memory: 4Gi
        limits:
          cpu: "0.75"
          memory: 4Gi

    - name: redis
      image: ${SPCS_REDIS_IMAGE}
      command: ["redis-server","--save","","--appendonly","no"]
      resources:
        requests:
          cpu: "0.25"
          memory: 256Mi
        limits:
          cpu: "0.25"
          memory: 1Gi

  endpoints:
    - name: ui
      port: 8088
      public: true

  # If your managed Postgres hostname requires egress allowlisting, attach an EAI here.
  externalAccess:
    integrations:
      - ${PG_EAI_NAME}

  volumes:
    - name: superset-config
      source: stage
      stageConfig:
        name: "${CONFIG_STAGE}"
