spec:
  containers:
    - name: superset
      image: ${SPCS_IMAGE}
      env:
        SUPERSET_CONFIG_PATH: /config/superset_config.py
        SUPERSET_DB_URI: postgresql+psycopg2://superset:superset@postgres:5432/superset
        SUPERSET_REDIS_HOST: redis
        SUPERSET_REDIS_PORT: "6379"
      secrets:
        - snowflakeSecret: ${SECRET_SUPERSET_SECRET_KEY}
          secretKeyRef: secret_string
          envVarName: SUPERSET_SECRET_KEY
        - snowflakeSecret: ${SECRET_SUPERSET_FERNET_KEY}
          secretKeyRef: secret_string
          envVarName: SUPERSET_FERNET_KEY
      volumeMounts:
        - name: superset-config
          mountPath: /config
      resources:
        requests:
          cpu: "0.5"
          memory: 2Gi
        limits:
          cpu: "0.5"
          memory: 2Gi

    - name: postgres
      image: ${SPCS_POSTGRES_IMAGE}
      env:
        POSTGRES_DB: superset
        POSTGRES_USER: superset
        POSTGRES_PASSWORD: superset
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      resources:
        requests:
          cpu: "0.25"
          memory: 1Gi
        limits:
          cpu: "0.5"
          memory: 2Gi

    - name: redis
      image: ${SPCS_REDIS_IMAGE}
      command: ["redis-server","--save","","--appendonly","no"]
      resources:
        requests:
          cpu: "0.25"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi

  endpoints:
    - name: ui
      port: 8088
      public: true

  capabilities:
    securityContext:
      executeAsCaller: true

  volumes:
    - name: superset-config
      source: stage
      stageConfig:
        name: "${CONFIG_STAGE}"
    - name: pgdata
      source: block
      size: 5Gi
